src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/home', function() {
    return redirect()->route('dashboard');
});

Route::get('/', 'HomeController@index')->name('home');

Route::get('/not-authorised', 'HomeController@notAuthorised')->name('not-authorised');


Route::group(['middleware'=>['auth']], function() {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('reports', 'ReportController');
    Route::get('/reports/{report}/view', 'ReportController@view')->name('reports.view');

    Route::get('/tenants/select/{tenant}', 'TenantController@select')->name('tenant.select');

    Route::resource('users','UserController');
    Route::resource('groups','GroupController');
    Route::resource('tenants', 'TenantController');

});



// don't use default auth routes, as we don't want people to be able to register themselves!
//Auth::routes();
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

Route::get('/password/invite', 'Auth\InvitePasswordController@showLinkRequestForm')->name('password.invite');

Route::get('/invite/reject/{user}', 'Auth\InvitePasswordController@rejectInvite')->name('invite.reject');

Route::post('/password/invite', 'Auth\InvitePasswordController@sendInviteEmail')->name('password.send');
Route::get('/password/create/{token}', 'Auth\CreatePasswordController@showCreateForm')->name('password.create');
Route::post('/password/create', 'Auth\CreatePasswordController@create')->name('password.store');

//The AAD login routes
Route::get('/login/with-aad', 'Auth\AzureActiveDirectoryController@loginStart')->name('login.aad.start');
Route::get('/login/with-aad/{application?}', 'Auth\AzureActiveDirectoryController@loginResponse')->name('login.aad.response');
Route::get('/logout/with-aad/{application?}', 'Auth\AzureActiveDirectoryController@logout');


/***********************************************************************************************************************
 *
 * API Routes (for AJAX/Axios/Vue calls
 *
 */
Route::group(['prefix'=>'/web-api/', 'middleware'=>'auth'], function() {
    Route::get('tenants', 'ApiController@tenants');
    Route::get('groups', 'ApiController@groups');
    Route::get('tenants/{tenant}/groups', 'ApiController@groups');
    Route::get('powerbi/groups', 'ApiController@pbiGroups');
    Route::get('powerbi/groups/{group}/reports', 'ApiController@pbiReports');
    Route::get('reports/{report}/token', 'ApiController@pbiReportToken');
});

src/resources/views/partials/nav/main-menu-globaladmin.blade.php
{{--Administration--}}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="/users">Users</a></li>
        <li><a href="/tenants">Tenants</a></li>
        <li><a href="/reports">Reports</a></li>
        <li><a href="/groups">Groups</a></li>

    </ul>
</li>

src/resources/views/partials/nav/main-menu-guest.blade.php
<!--<li><a href="/info/about-site">What can I do?</a></li>
<li><a href="/info/about-company">About Us</a></li>-->

src/resources/views/partials/nav/main-menu-user.blade.php
{{--Reports--}}
@if (count($reports) > 0)
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">Reports<span class="caret"></span></a>
        <ul class="dropdown-menu">

            @foreach($reports as $report)
                <li><a href="{{ route('reports.view', $report) }}">{{$report->name}}</a></li>
            @endforeach

        </ul>
    </li>
@else
    <li><a href="{{route('dashboard')}}">Dashboard</a></li>
@endif

src/resources/views/partials/nav/right-menu-admin.blade.php
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        Selected User Groups:

        @if (session()->has('selectedUserGroup'))
            {{ count(session()->get('selectedUserGroup')) }}
        @else
            All
        @endif

        <span class="caret"></span>
    </a>

    <ul class="dropdown-menu customer-select" role="menu">
        @if(session()->has('selectedUserGroup') AND session()->get('selectedUserGroup'))
            <li>Filtered to:</li>
            <li class="customer-link"><a href="{{ route('groups.show', [$selectedGroupId]) }}">{{$selectedGroupName}}</a></li>
        @endif
        <li><a href="{{ route('groups.select-none') }}">Show all User Groups</a></li>
        <li><a href="{{ route('groups.select-list') }}">Choose User Group</a></li>
    </ul>
</li>

src/resources/views/partials/nav/right-menu-guest.blade.php
<ul class="nav navbar-nav navbar-right">

<li><a href="{{ route('login') }}">Login</a></li>

</ul>

src/resources/views/partials/nav/right-menu-user.blade.php
    <ul class="nav navbar-nav navbar-right">
{{--
        @can('seeAdminMenuOptions')
            <li class="user-group-selector" >
                <bytes-user-group-selector
                        options-string="{{$userGroups}}"
                        title="User Group"
                        initial-id="{{$selectedUserGroupID}}">
                </bytes-user-group-selector>
            </li> --}}{{--app--}}{{--

        @endcan--}}

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    {{ Auth::user()->name }} <span class="glyphicon glyphicon-user" aria-hidden="true"
                                                   style="margin:0px 10px;"></span> <span class="caret"></span>
                </a>

                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                            Logout
                        </a>


                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                    {{-- only show list of tenants if user can access more than one --}}
                    @if (isset($allowedTenants) AND count($allowedTenants)>1)
                        <hr>
                        @foreach($allowedTenants as $tenant)
                            <li>
                                <a href="{{ route('tenant.select',$tenant) }}">
                                    {{$tenant->name}}
                                    @if(session('selectedTenant') == $tenant->id)
                                        <span class="selected-tenant">*</span>
                                    @endif

                                </a>
                            </li>
                        @endforeach
                    @endif


                </ul>
            </li>
    </ul>