src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/home', function() {
    return redirect()->route('dashboard');
});

Route::get('/', 'HomeController@index')->name('home');

Route::get('/not-authorised', 'HomeController@notAuthorised')->name('not-authorised');


Route::group(['middleware'=>['auth']], function() {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('reports', 'ReportController');
    Route::get('/reports/{report}/view', 'ReportController@view')->name('reports.view');

    Route::get('/tenants/select/{tenant}', 'TenantController@select')->name('tenant.select');

    Route::resource('users','UserController');
    Route::resource('groups','GroupController');
    Route::resource('tenants', 'TenantController');

});



// don't use default auth routes, as we don't want people to be able to register themselves!
//Auth::routes();
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

Route::get('/password/invite', 'Auth\InvitePasswordController@showLinkRequestForm')->name('password.invite');

Route::get('/invite/reject/{user}', 'Auth\InvitePasswordController@rejectInvite')->name('invite.reject');

Route::post('/password/invite', 'Auth\InvitePasswordController@sendInviteEmail')->name('password.send');
Route::get('/password/create/{token}', 'Auth\CreatePasswordController@showCreateForm')->name('password.create');
Route::post('/password/create', 'Auth\CreatePasswordController@create')->name('password.store');

//The AAD login routes
Route::get('/login/with-aad', 'Auth\AzureActiveDirectoryController@loginStart')->name('login.aad.start');
Route::get('/login/with-aad/{application?}', 'Auth\AzureActiveDirectoryController@loginResponse')->name('login.aad.response');
Route::get('/logout/with-aad/{application?}', 'Auth\AzureActiveDirectoryController@logout');


/***********************************************************************************************************************
 *
 * API Routes (for AJAX/Axios/Vue calls
 *
 */
Route::group(['prefix'=>'/web-api/', 'middleware'=>'auth'], function() {
    Route::get('tenants', 'ApiController@tenants');
    Route::get('groups', 'ApiController@groups');
    Route::get('tenants/{tenant}/groups', 'ApiController@groups');
    Route::get('powerbi/groups', 'ApiController@pbiGroups');
    Route::get('powerbi/groups/{group}/reports', 'ApiController@pbiReports');
    Route::get('reports/{report}/token', 'ApiController@pbiReportToken');
});

src/app/Models/Group.php
<?php

namespace App\Models;

use App\Traits\URLObfuscation;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Collection;
use DB;

class Group extends Model
{
    use SoftDeletes;
    use URLObfuscation;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'tenant_id'
    ];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function tenant()
    {
        return $this->belongsTo(Tenant::class );
    }


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function reports()
    {
        return $this->hasMany(Report::class );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    /**
     * When a Tenant is soft deleted cascade delete it's and Reports
     */
    public function deleteAndCascade(){

        DB::transaction(function() {

            foreach ($this->reports as $report) {
                $report->delete();
            }

            $this->delete();

        });

    }


}

src/app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

//Models
use App\Models\Group;
use App\Models\Tenant;

//Form Requests
use App\Http\Requests\StoreGroup;

class GroupController extends Controller
{

    /**
     * Ensure that a tenant is selected
     * DashboardController constructor.
     */
    public function __construct()
    {
        $this->middleware('tenantSelected');
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $this->authorize('index', Group::class);
        $groups = optional(Tenant::selectedTenant())->groups;
        return view('groups.index', compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Group::class);
        $group = new Group();
        $tenants = Tenant::getObfuscatedTenants();

        return view('groups.create', compact('group', 'tenants'));
    }

    /**
     * Store a newly created resource in storage
     * @param StoreGroup $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreGroup $request)
    {
        //auth in form request

        $group = new Group();
        $group->name = $request->name;
        $group->description = $request->description;
        $group->tenant_id = $request->tenant_id;
        $group->save();

        return redirect()->route('groups.show', [$group]);
    }

    /**
     * Display the specified resource.
     * @param Group $group
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Group $group)
    {
        $this->authorize('show', $group);

        $users = $group->users;

        return view('groups.show', compact('group','users'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param Group $group
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Group $group)
    {
        $this->authorize('edit', $group);
        $tenants = Tenant::getObfuscatedTenants();

        return view('groups.edit', compact('group', 'tenants'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Tenant  $tenant
     * @return \Illuminate\Http\Response
     */
    public function update(StoreGroup $request, Group $group)
    {
        $group->name = $request->name;
        $group->description = $request->description;
        $group->tenant_id = $request->tenant_id;
        $group->save();

        return redirect()->route('groups.show', [$group]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Tenant  $tenant
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     * @throws \Exception
     */
    public function destroy(Group $group)
    {
        $this->authorize('destroy', $group);

       $group->deleteAndCascade();

        return response()->json([
            'status' => 'ok',
            'message' =>  'tenant '.$group->getRouteKey().' deleted'
        ], 200);

    }
}

src/resources/views/groups/create.blade.php
@extends('layouts/main')

@section('title', 'Add a Group')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add a Group</div>
                    <div class="panel-body">
                        @include('partials/forms/errors')
                        <form class="form-horizontal" role="form" method="POST" action="{{route('groups.store')}} ">
                            {{ csrf_field() }}

                            @include('groups/partials/fields')


                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Add Group
                                    </button>

                                    <a class="btn btn-link" href="{{ route('groups.index') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>

        </div>
    </div>

@endsection

src/resources/views/groups/edit.blade.php
@extends('layouts/main')

@section('title', 'Edit Group')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit Group</div>
                    <div class="panel-body">
                        @include('partials/forms/errors')
                        <form class="form-horizontal" role="form" method="POST"
                              action="{{ route('groups.update',[$group]) }}">
                            <input type="hidden" name="_method" value="PUT">
                            {{ csrf_field() }}


                            @include('groups/partials/fields')
                          
                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Update
                                    </button>

                                    <a class="btn btn-link" href="{{ route('groups.index') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>

        </div>
    </div>

@endsection

src/resources/views/groups/index.blade.php
@extends('layouts/main')

@section('title', 'List Groups')


@section('include-css')
    <link  href="{{ asset('css/datatables.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('css/responsive.dataTables.min.css') }}" rel="stylesheet"/>
@endsection

@section('content')



<div class="container-fluid">

    <div class="row">


        {{--The column for search and actions--}}
        <div class="col-xs-12 col-md-2   col-md-push-10  col-lg-2 col-lg-push-10 hide-while-loading">

            {{--The search panel--}}
            <div class="panel panel-default">
                <div class="panel-heading">Search Groups</div>
                <div class="panel-body">
                    <div class="form-group">
                        {{--<label for="search">Search:</label>--}}
                        <input id= "datatable-search" type="search" class="form-control" id="email">
                    </div>
                </div> {{--body--}}
            </div> {{--panel--}}


            {{--The actions panel--}}
            <div class="panel panel-default">
                <div class="panel-heading">Actions</div>
                <div class="panel-body">

                    <a href="{{ route('groups.create') }}" class="btn btn-success btn-block">New</a>
                    <button type="button" id="edit-button" class="btn btn-primary btn-block" onclick="btnEditClick()" disabled>Edit</button>
                    <button type="button" id="delete-button" class="btn btn-danger btn-block" onclick="btnDeleteClick()" disabled>Delete</button>
                    <button type="button" id="view-button" class="btn btn-primary btn-block" onclick="btnViewClick()" disabled>View Details</button>
                    <br>

                </div> {{--body--}}
            </div> {{--panel--}}
        </div> {{--col--}}




        {{--The Datatable panel--}}
        <div class="col-xs-12 col-md-pull-2 col-md-10 col-lg-offset-2 col-lg-8 col-lg-pull-2">

                <table class="table table-bordered table-striped hide-while-loading" id ="groups" style="width:100%">
                    <thead>
                        <tr>
                            <th class="negative">ID</th>
                            <th class="negative">Name</th>
                            <th class="negative">Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($groups as $group)
                                <tr>
                                    <td>{{ $group->getRouteKey() }}</td>
                                    <td>{{ $group->name }}</td>
                                    <td>{{ $group->description }}</td>
                                </tr>
                        @endforeach
                    </tbody>
                </table>

        </div> {{--main col--}}


    </div> {{--row--}}



</div>

@endsection

@section('scripts')
    <script src="{{ asset('js/datatables.min.js') }}"></script>
    <script src="{{ asset('js/datatables.select.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.responsive.min.js') }}"></script>

    <script src="{{ mix('js/groups-common.js') }}"></script>
    <script src="{{ mix('js/groups-index.js') }}"></script>
    <script type="text/javascript">
        var selectedTenantName = "{{ optional(App\Models\Tenant::selectedTenant())->name }}";
    </script>
@endsection

src/resources/views/groups/show.blade.php
@extends('layouts/main')

@section('title', 'Group')


@section('include-css')
    <link  href="{{ asset('css/datatables.min.css') }}" rel="stylesheet" />
@endsection

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Group</div>
                    <div class="panel-body">

                        {{--Name--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Group</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$group->name}}</span>
                            </div>
                        </div>

                        {{--Description--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Description</strong>
                            </div>

                            <div class="col-md-6 link">
                                {{$group->description}}
                            </div>
                        </div>


                        {{--Tenant--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Tenant</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$group->tenant->name}}</span>
                            </div>
                        </div>

                    </div>
                    <div class="panel-footer">

                        @can('update',$group)
                            <a class="btn btn-primary" href="{{route('groups.edit', [$group]) }}">Edit</a>
                        @endcan

                        @can('destroy',$group)
                            <a class="btn btn-danger" onclick="destroy('{{$group->getRouteKey()}}')">Delete</a>
                        @endcan


                    </div>
                </div> {{--panel--}}

                @include('groups/partials/user-list')


                <div>
                    <a class="btn btn-default" a href="{{ route('groups.index') }}"><span class="icon-return"></span>Back</a>
                </div>


            </div>
        </div> {{--container--}}
    </div>
@endsection


@section('scripts')
    <script src="{{ asset('js/datatables.min.js') }}"></script>
    <script src="{{ mix('js/groups-common.js') }}"></script>
@endsection


@section('script')
    <script>
        $(document).ready(function() {
            $('#users').DataTable();
        } );

    </script>
@endsection

src/resources/views/groups/view.blade.php
@extends('layouts.fullscreen')

@section('title', 'View Report')

@section('content')

<iframe id="iframe_pbi" width="100%" height="100%" src="" frameborder="0" allowFullScreen="true"></iframe>

@endsection


@section('scripts')
<script type="application/javascript">
<!--
    var token = '{{ $report->token }}';
    var auth = '{{ md5($report->token . time() . str_random(16)) }}';

    var pbi_url = 'https://app.powerbi.com/view?r='+token+'&auth='+auth;

    document.getElementById('iframe_pbi').src = pbi_url;
-->
</script>

@endsection