src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/home', function() {
    return redirect()->route('dashboard');
});

Route::get('/', 'HomeController@index')->name('home');

Route::get('/not-authorised', 'HomeController@notAuthorised')->name('not-authorised');


Route::group(['middleware'=>['auth']], function() {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('reports', 'ReportController');
    Route::get('/reports/{report}/view', 'ReportController@view')->name('reports.view');

    Route::get('/tenants/select/{tenant}', 'TenantController@select')->name('tenant.select');

    Route::resource('users','UserController');
    Route::resource('groups','GroupController');
    Route::resource('tenants', 'TenantController');

});



// don't use default auth routes, as we don't want people to be able to register themselves!
//Auth::routes();
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

Route::get('/password/invite', 'Auth\InvitePasswordController@showLinkRequestForm')->name('password.invite');

Route::get('/invite/reject/{user}', 'Auth\InvitePasswordController@rejectInvite')->name('invite.reject');

Route::post('/password/invite', 'Auth\InvitePasswordController@sendInviteEmail')->name('password.send');
Route::get('/password/create/{token}', 'Auth\CreatePasswordController@showCreateForm')->name('password.create');
Route::post('/password/create', 'Auth\CreatePasswordController@create')->name('password.store');

//The AAD login routes
Route::get('/login/with-aad', 'Auth\AzureActiveDirectoryController@loginStart')->name('login.aad.start');
Route::get('/login/with-aad/{application?}', 'Auth\AzureActiveDirectoryController@loginResponse')->name('login.aad.response');
Route::get('/logout/with-aad/{application?}', 'Auth\AzureActiveDirectoryController@logout');


/***********************************************************************************************************************
 *
 * API Routes (for AJAX/Axios/Vue calls
 *
 */
Route::group(['prefix'=>'/web-api/', 'middleware'=>'auth'], function() {
    Route::get('tenants', 'ApiController@tenants');
    Route::get('groups', 'ApiController@groups');
    Route::get('tenants/{tenant}/groups', 'ApiController@groups');
    Route::get('powerbi/groups', 'ApiController@pbiGroups');
    Route::get('powerbi/groups/{group}/reports', 'ApiController@pbiReports');
    Route::get('reports/{report}/token', 'ApiController@pbiReportToken');
});

src/app/Models/User.php
<?php

namespace App\Models;


use App\Traits\URLObfuscation;

//Laravel
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;


/**
 * Class User
 * @package App\Models
 * @property integer $id
 *
 */
class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    use URLObfuscation;


    const STATUS_INVITED = 0;
    const STATUS_REGISTERED = 5;
    const STATUS_ACTIVE = 10;

    const STATUS_REJECTED = -5;
    const STATUS_INACTIVE = -10;
    const STATUS_SUSPENDED = -100;
    const STATUS_DELETED = -120;

    const STATUS_ALL = [
        self::STATUS_REJECTED,
        self::STATUS_DELETED,
        self::STATUS_SUSPENDED,
        self::STATUS_INACTIVE,
        self::STATUS_INVITED,
        self::STATUS_REGISTERED,
        self::STATUS_ACTIVE,
    ];

    const ROLE_GLOBAL_ADMIN = 'GLOBAL_ADMIN';
    const ROLE_RESELLER_ADMIN = 'RESELLER_ADMIN';
    const ROLE_TENANT_ADMIN = 'TENANT_ADMIN';
    const ROLE_USER = 'USER';
    const ROLE_ALL = [
        self::ROLE_USER, self::ROLE_TENANT_ADMIN, self::ROLE_RESELLER_ADMIN, self::ROLE_GLOBAL_ADMIN
    ];


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'tenant_id',
        'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * A user has many groups
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function groups()
    {
        return $this->belongsToMany(Group::class);
    }


    /**
     * A user belongs to many tenants
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tenants()
    {
        return $this->belongsToMany(Tenant::class);
    }

    /**
     * This is how we currently determine which tenant the
     * user "belongs to". This will change when they can have multiple.
     *
     * @return null
     *
     */
    public function  defaultTenant()
    {
        if($this->tenants->count() > 0){
            return $this->tenants->first();
        }else {
            return null;
        }
    }


    /**
     * Selects the default Tenant for this user
     * if they don't have one, kick them out
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function selectDefaultTenant()
    {
        $passed = false;

        if ($this->defaultTenant()) {
            session()->put('selectedTenant', $this->defaultTenant()->id);
            $passed = true;
        }

        return $passed;
    }


    /**
     * Check that the selected tenant exists
     * if it doesn't select the default for this user
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function checkSelectedTenantExists()
    {
        $tenant = Tenant::find(session('selectedTenant'));

        $passed = ($tenant ? true:false);
        return $passed;
    }



    /**
     * Check that the default tenant for this user exists
     */
    public function checkDefaultExists()
    {
        $tenant = Tenant::find(session('selectedTenant'));

        $passed = ($tenant ? true:false);
        return $passed;
    }


    /**
     * Global admins can see all tenants
     *  other users need a tenant_user record
     * @return Tenant[]|\Illuminate\Database\Eloquent\Collection|mixed
     */
    public function allowedTenants()
    {
        if($this->role == User::ROLE_GLOBAL_ADMIN) {
            return Tenant::all();
        } else {
            return $this->tenants;
        }
    }


    /**
     * Get all the reports this user has access to.
     * This is all the reports for all their groups.
     * @return Report[]|\Illuminate\Database\Eloquent\Collection
     */
    public function allReports()
    {
        $groups = $this->groups->pluck('id')->toArray();
        $result = Report::whereIn('group_id',$groups)->get();

        return $result;
    }

    /**
     * @return array
     */
    public static function getRoles()
    {
        $userRoles = null;

        foreach (User::ROLE_ALL as $role) {
            $userRoles[$role] = ucwords(strtolower(str_replace('_', ' ', $role)));
        }

        return $userRoles;
    }





    /**
     *
     * Just check the password reset token for a new user.
     * @param string $token
     * @return bool
     */
    public function checkToken(string $token)
    {
        $passed = false;

        $resetRecord = DB::table('password_resets')
            ->select('token')
            ->where('email', '=', $this->email)
            ->first();

        if (isset($resetRecord)) {

            if (Hash::check($token, $resetRecord->token)) {
                $passed = true;
            }
        }

        return $passed;
    }

    /**
     * @param $email
     * @return User
     */
    static public function findByEmail($email)
    {
        return self::where('email', '=', $email)->firstOrFail();
    }

    /**
     * @return string
     */
    public function statusString()
    {
        switch ($this->status) {
            case self::STATUS_INVITED:
                return 'Invited';
            case self::STATUS_REGISTERED:
                return 'Registered';
            case self::STATUS_ACTIVE:
                return 'Active';
            case self::STATUS_INACTIVE:
                return 'Inactive';
            case self::STATUS_SUSPENDED:
                return 'Suspended';
        }
        return 'INVALID';
    }

    /**
     * @return string
     */
    public function roleString()
    {
        return ucwords(strtolower(str_replace('_', ' ', $this->role)));
    }

    /**
     * Checks that this user is a Global Admin.
     * @return bool
     */
    public function isGlobalAdmin()
    {
        return self::ROLE_GLOBAL_ADMIN == $this->role;
    }

    /**
     * @param null $for
     * @return bool
     */
    public function isResellerAdmin($for = NULL)
    {
        if (is_null($for)) {
            // just check if user has reseller admin role
            return self::ROLE_RESELLER_ADMIN == $this->role;
        }

    }


}

src/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Response;

//Form Requests
use App\Http\Requests\StoreUser;

//Models
use App\Models\User;
use App\Models\Tenant;

class UserController extends Controller
{

    /**
     * Ensure that a tenant is selected
     * DashboardController constructor.
     */
    public function __construct()
    {
        $this->middleware('tenantSelected');
    }

    /**
     * Display list of users.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $this->authorize('index', User::class);
        $users = optional(Tenant::selectedTenant())->users;
        return view('users.index', compact('users'));
    }

    /**
     * Show the form to create new.
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', User::class);
        $roles = User::getRoles();
//        $tenants = Tenant::getObfuscatedTenants();
        $currentTenant = Tenant::selectedTenant();
        $user = new User();

        $assignedGroups = collect();
//        $allGroups = Tenant::selectedTenant()->groups;

        return view('users.create', compact('roles', 'user', 'currentTenant', 'assignedGroups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreUser $request#
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role = $request->role;
        $user->status = User::STATUS_INVITED;
        $user->save();
        $user->groups()->sync($request->groups);
        $user->tenants()->attach($request->tenant_id);


        // TODO: make this queued & set up queue workers on server


        return redirect()->route('users.show', [$user]);
    }


    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(User $user)
    {
        $this->authorize('show', $user);

        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param User $user
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(User $user)
    {
        $this->authorize('edit', $user);
        $roles = User::getRoles();
        $currentTenant = Tenant::selectedTenant();
        $assignedGroups = $user->groups;
//        $allGroups = Tenant::selectedTenant()->groups;

        return view('users.edit', compact('user', 'roles', 'currentTenant', 'assignedGroups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoreUser $request
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUser $request, User $user)
    {

        $user->name = $request->name;
        $user->email = $request->email;
        $user->role = $request->role;
        $user->tenants()->sync([$request->tenant_id]);
        $user->groups()->sync($request->groups);
        $user->save();


        //getOriginal?

        return redirect()->route('users.show', [$user]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     * @throws \Exception
     */
    public function destroy(User $user)
    {
        $this->authorize('destroy', $user);

        if( $user->is(auth()->user()) ){ //cannot delete yourself
            $message = "You cannot delete your own user.";
            session()->flash('error', $message);
            $status = "error";
            $statusCode = 403;

        }else{
            $user->delete();


            $status = "error";
            $message = "User  {$user->getRouteKey()}  deleted";

            $statusCode = 200;

        }


        return   response()->json([
            'status' => $status,
            'message' => $message
        ], $statusCode);

    }


}

src/resources/views/users/create.blade.php
@extends('layouts/main')

@section('title', 'Add a User')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add a User</div>
                    <div class="panel-body">
                        @include('partials/forms/errors')
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('users.store') }}">
                            {{ csrf_field() }}

                            @include('users/partials/fields')

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Add User
                                    </button>

                                    <a class="btn btn-link" href="{{ route('users.index') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>

        </div>
    </div>

@endsection

src/resources/views/users/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit a User')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit User</div>
                    <div class="panel-body">
                        @include('partials/forms/errors')
                        <form class="form-horizontal" role="form" method="POST"
                              action="{{ route('users.update',[$user->getRouteKey()]) }}">
                            <input type="hidden" name="_method" value="PUT">
                            {{ csrf_field() }}

                            @include('users/partials/fields')

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Update User
                                    </button>

                                    <a class="btn btn-link" href="{{ route('users.index') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>

                        </form>
                    </div> {{--panel body--}}
            </div> {{--panel--}}
            </div>
        </div> {{--row--}}
    </div> {{--container--}}

@endsection

src/resources/views/users/index.blade.php
@extends('layouts.main')

@section('title', 'List Users')


@section('include-css')
    <link href="{{ asset('css/datatables.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/responsive.dataTables.min.css') }}" rel="stylesheet"/>
@endsection

@section('content')

    <div class="container-fluid">

        <div class="row">
            {{--The column for search and actions--}}
            <div class="col-xs-12 col-md-2   col-md-push-10  col-lg-2 col-lg-push-10 hide-while-loading">

                {{--The search panel--}}
                    <div class="panel panel-default">
                        <div class="panel-heading">Search Users</div>
                        <div class="panel-body">
                            <div class="form-group">
                                {{--<label for="search">Search:</label>--}}
                                <input id= "datatable-search" type="search" class="form-control" id="email">
                            </div>
                        </div> {{--body--}}
                    </div> {{--panel--}}

                    {{--The actions panel--}}
                    <div class="panel panel-default">
                        <div class="panel-heading">Actions</div>
                        <div class="panel-body">
                            <a href="{{ route('users.create') }}" class="btn btn-success btn-block">New</a>
                            <button type="button" id="edit-button" class="btn btn-primary btn-block" onclick="btnEditClick()" disabled>Edit</button>
                            <button type="button" id="delete-button" class="btn btn-danger btn-block" onclick="btnDeleteClick()" disabled>Delete</button>
                            <button type="button" id="view-button" class="btn btn-primary btn-block" onclick="btnViewClick()" disabled>View Details</button>
                            <br>
                        </div> {{--body--}}
                    </div> {{--panel--}}

            </div> {{--col--}}


            {{--The Datatable panel--}}
            <div class="col-xs-12 col-md-pull-2 col-md-10 col-lg-offset-2 col-lg-8 col-lg-pull-2">
                <table class="table table-striped table-bordered dataTable hide-while-loading" id="users" style="width:100%">
                    <thead>
                        <tr>
                            <th class="negative" >ID</th>
                            <th class="negative" >Name</th>
                            <th class="negative" >Role</th>
                            <th class="negative" >Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->getRouteKey() }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->roleString() }}</td>
                            <td>{{ $user->statusString() }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div> {{--Datatable panel--}}

        </div> {{--row--}}

    </div> {{--container--}}

@endsection

@section('scripts')
    <script src="{{ asset('js/datatables.min.js') }}"></script>
    <script src="{{ asset('js/datatables.select.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.responsive.min.js') }}"></script>


    <script src="{{ mix('js/users-common.js') }}"></script>
    <script src="{{ mix('js/users-index.js') }}"></script>
    <script type="text/javascript">
        var selectedTenantName = "{{ optional(App\Models\Tenant::selectedTenant())->name }}";
    </script>
@endsection

src/resources/views/users/show.blade.php
@extends('layouts.main')

@section('title', 'User')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">User</div>
                    <div class="panel-body">

                        {{--Name--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Name</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$user->name}}</span>
                            </div>
                        </div>

                        {{--Email--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Email</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$user->email}}</span>
                            </div>
                        </div>

                        {{--Tenant--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Tenant</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$user->defaultTenant()->name}}</span>
                            </div>
                        </div>

                        {{--Role--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Role</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$user->roleString()}}</span>
                            </div>
                        </div>


                        {{--Groups--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Groups</strong>
                            </div>
                            <div class="col-md-6">
                                <span>
                                    {{$user->groups->pluck('name')->implode(',')}}
                                </span>
                            </div>
                        </div>



                    </div>
                    <div class="panel-footer">
                        <a class="btn btn-primary mr1" href="{{ route('users.edit', [$user]) }}">Edit User</a>

                        <a class="btn btn-danger" onclick="destroy('{{$user->getRouteKey()}}')">Delete User</a>

                    </div>
                </div> {{--panel--}}



                <div>
                    <a class="btn btn-default" a href="{{ route('users.index') }}"><span class="icon-return"></span>Back to User list</a>
                </div>



            </div>
        </div> {{--container--}}
    </div>
@endsection

@section('script')

    <script src="{{ mix('js/users-common.js') }}"></script>

@endsection